package mx.ipn.upiicsa.calculadora.calculator;

public class Calculator extends javax.swing.JFrame {
    //region GlobalVariables
    //Valores "En memoria RAM"
    private int resultado;
    private int valor;
    //endregion
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlDisplay = new javax.swing.JPanel();
        jlblResultado = new javax.swing.JLabel();
        jpnlButtons = new javax.swing.JPanel();
        jbtnOperatorPlus = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtnOperatorMinus = new javax.swing.JButton();
        jbtnOperatorProduct = new javax.swing.JButton();
        jbtnOperatorDivision = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnlDisplay.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));

        jlblResultado.setText("jLabel1");

        javax.swing.GroupLayout jpnlDisplayLayout = new javax.swing.GroupLayout(jpnlDisplay);
        jpnlDisplay.setLayout(jpnlDisplayLayout);
        jpnlDisplayLayout.setHorizontalGroup(
            jpnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDisplayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblResultado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlDisplayLayout.setVerticalGroup(
            jpnlDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDisplayLayout.createSequentialGroup()
                .addComponent(jlblResultado)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        jbtnOperatorPlus.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtnOperatorPlus.setText("+");
        jbtnOperatorPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnOperatorPlusMouseClicked(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn1.setText("1");

        jbtn2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn2.setText("2");

        jbtn3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn3.setText("3");

        jbtn4.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn4.setText("4");

        jbtn5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn5.setText("5");

        jbtn6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn6.setText("6");

        jbtn8.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn8.setText("8");

        jbtn9.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn9.setText("9");

        jbtn7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn7.setText("7");

        jbtnOperatorMinus.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtnOperatorMinus.setText("-");

        jbtnOperatorProduct.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtnOperatorProduct.setText("X");
        jbtnOperatorProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnOperatorProductMouseClicked(evt);
            }
        });

        jbtnOperatorDivision.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtnOperatorDivision.setText("/");
        jbtnOperatorDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnOperatorDivisionMouseClicked(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jbtn0.setText("0");

        jbtn10.setFont(new java.awt.Font("sansserif", 0, 21)); // NOI18N
        jbtn10.setText("CE");

        javax.swing.GroupLayout jpnlButtonsLayout = new javax.swing.GroupLayout(jpnlButtons);
        jpnlButtons.setLayout(jpnlButtonsLayout);
        jpnlButtonsLayout.setHorizontalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                                .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                                .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnlButtonsLayout.createSequentialGroup()
                                .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbtnOperatorMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtnOperatorDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jpnlButtonsLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jbtnOperatorPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnOperatorProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jpnlButtonsLayout.setVerticalGroup(
            jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1)
                    .addComponent(jbtn2)
                    .addComponent(jbtn3)
                    .addComponent(jbtn10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4)
                    .addComponent(jbtn5)
                    .addComponent(jbtn6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jbtnOperatorMinus)
                    .addComponent(jbtnOperatorDivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOperatorPlus)
                    .addComponent(jbtnOperatorProduct)
                    .addComponent(jbtn0))
                .addGap(117, 117, 117))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnlButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOperatorPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnOperatorPlusMouseClicked
        jlblResultado.setText("Probando");
    }//GEN-LAST:event_jbtnOperatorPlusMouseClicked

    private void jbtnOperatorProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnOperatorProductMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnOperatorProductMouseClicked

    private void jbtnOperatorDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnOperatorDivisionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnOperatorDivisionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn10;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnOperatorDivision;
    private javax.swing.JButton jbtnOperatorMinus;
    private javax.swing.JButton jbtnOperatorPlus;
    private javax.swing.JButton jbtnOperatorProduct;
    private javax.swing.JLabel jlblResultado;
    private javax.swing.JPanel jpnlButtons;
    private javax.swing.JPanel jpnlDisplay;
    // End of variables declaration//GEN-END:variables
}
